const data = {
  products: [
    {
      slug: 'free-shirt',
      name: 'Free Shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      slug: 'fit-shirt',
      name: 'Fit Shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      slug: 'slim-shirt',
      name: 'Slim Shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      slug: 'heavy-shirt',
      name: 'Heavy Shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 80,
      brand: 'Adidas',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      slug: 'golf-shirt',
      name: 'Golf Shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 70,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      slug: 'classic-pants',
      name: 'Classic Pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 75,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      slug: 'heavy-pants',
      name: 'Heavy Pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 85,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      slug: 'fit-pants',
      name: 'Fit Pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 85,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
  ],
}

export default data
